name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  snyk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk security test
        run: snyk test --all-projects --json > snyk-results.json

      - name: Upload Snyk results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-results
          path: snyk-results.json
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci

  deliver:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Push Docker image to Docker Hub
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t yourdockerhubusername/my-image-name:latest .
            docker push yourdockerhubusername/my-image-name:latest
